```{r}
library(rio)
library(dplyr)
library(usethis)
path_i <- "~/Documents/Estadistica/estadisticaFcaUnl/data/internal"
```



## Pesada terneros
```{r}
pesada_terneros <- import(file.path(path_i, "pesada_terneros.xlsx"))
str(pesada_terneros)
```
```{r}
use_data(pesada_terneros, overwrite = TRUE)
```

## superficies_EAP
```{r}
superficies_EAP <- read.fwf(file.path(path_i, "superficies_EAP.txt"), widths = c(23, 10, 20), header = FALSE, skip = 1, strip.white = TRUE, col.names = c("Departamento", "Cant_EAP", "Sup_promedio")) %>%
    mutate(Departamento = gsub('"', "", Departamento))
str(superficies_EAP)
```
```{r}
use_data(superficies_EAP, overwrite = TRUE)
```

## pesada_novillos
```{r}
pesada_novillos <- import(file.path(path_i, "pesada_novillos.xlsx")) %>%
    mutate(
        Fecha_Ingreso = as.Date(as.numeric(Fecha_Ingreso), origin = "1899-12-30"),
        Fecha = as.Date(as.numeric(Fecha), origin = "1899-12-30"),
        Hora = format(as.POSIXct(as.numeric(Hora) * 86400, origin = "1970-01-01", tz = "UTC"), "%H:%M:%S")
    )
str(pesada_novillos)
```
```{r}
use_data(pesada_novillos, overwrite = TRUE)
```

## tambos_2008_2015
```{r}
tambos_2008_2015 <- import(file.path(path_i, "tambos_2008-2015.xls"))
str(tambos_2008_2015)
```
```{r}
use_data(tambos_2008_2015, overwrite = TRUE)
```

## lotes_BA
```{r}
lotes_BA <- import(file.path(path_i, "Lotes_BA.xls"))
str(lotes_BA)
```
```{r}
use_data(lotes_BA, overwrite = TRUE)
```

## riesgo_arbolado
```{r}
riesgo_arbolado <- import(file.path(path_i, "riesgo_arbolado.xlsx"))
str(riesgo_arbolado)
```
```{r}
use_data(riesgo_arbolado, overwrite = TRUE)
```

## ryegrass
```{r}
ryegrass <- import(file.path(path_i, "ryegrass.txt"))
str(ryegrass)
```
```{r}
ryegrass <- ryegrass %>%
    mutate(
        planta = as.numeric(planta),
        longitud = as.numeric(longitud)
    )
str(ryegrass)
```
```{r}
use_data(ryegrass, overwrite = TRUE)
```

## tribolium
```{r}
tribolium <- import(file.path(path_i, "tribolium.txt"))
str(tribolium)
```
```{r}
use_data(tribolium, overwrite = TRUE)
```

## lisina_pollos
```{r}
lisina_pollos <- import(file.path(path_i, "lisina_pollos.txt"))
str(lisina_pollos)
```
```{r}
lisina_pollos <- lisina_pollos %>%
    mutate(
        Pollo = as.numeric(Pollo),
        Consumo = as.numeric(Consumo),
        Lisina = as.numeric(Lisina)
    )
str(lisina_pollos)
```
```{r}
use_data(lisina_pollos, overwrite = TRUE)
```

## productores
```{r}
productores <- import(file.path(path_i, "productores.xlsx"))
str(productores)
```
```{r}
use_data(productores, overwrite = TRUE)
```

## nitrogeno
```{r}
nitrogeno <- import(file.path(path_i, "nitrogeno.txt"))
str(nitrogeno)
```
```{r}
use_data(nitrogeno, overwrite = TRUE)
```

## novillos
```{r}
novillos <- import(file.path(path_i, "novillos.txt"))
str(novillos)
```
```{r}
use_data(novillos, overwrite = TRUE)
```

## pH_forestal
```{r}
pH_forestal <- import(file.path(path_i, "pH_forestal.txt"))
str(pH_forestal)
```
```{r}
use_data(pH_forestal, overwrite = TRUE)
```

## Lotes_CO
```{r}
lotes_CO <- import(file.path(path_i, "Lotes_CO.xls"))
str(lotes_CO)
```
```{r}
use_data(lotes_CO, overwrite = TRUE)
```

## pesada_novillos_tropa1
```{r}
pesada_novillos_tropa1 <- import(file.path(path_i, "Pesada 04-02-18 Tropa 1 Novillos LJ.csv"))
str(pesada_novillos_tropa1)
```
```{r}
use_data(pesada_novillos_tropa1, overwrite = TRUE)
```

## cabezas_ajo
```{r}
cabezas_ajo <- import(file.path(path_i, "cabezas_ajo.txt"))
str(cabezas_ajo)
```
```{r}
use_data(cabezas_ajo, overwrite = TRUE)
```

## cacahuates
```{r}
cacahuates <- import(file.path(path_i, "cacahuates.txt"))
str(cacahuates)
```
```{r}
use_data(cacahuates, overwrite = TRUE)
```

## datos_climaticos
```{r}
datos_climaticos <- import(file.path(path_i, "datos_climáticos.csv"))
str(datos_climaticos)
```
```{r}
use_data(datos_climaticos, overwrite = TRUE)
```

## ej7
```{r}
ej7 <- import(file.path(path_i, "ej7.txt"))
str(ej7)
```
```{r}
use_data(ej7, overwrite = TRUE)
```

## esparragos
```{r}
esparragos <- import(file.path(path_i, "esparragos.txt"))
str(esparragos)
```
```{r}
use_data(esparragos, overwrite = TRUE)
```

## forestal_calibracion
```{r}
forestal_calibracion <- import(file.path(path_i, "forestal_calibracion.txt"))
str(forestal_calibracion)
```
```{r}
use_data(forestal_calibracion, overwrite = TRUE)
```
